### ISSUE TITLE
Keep same packets visible within the viewport when not scrolling

### ISSUE THREAD

**Issue by bgrins** [firebug/rdp-inspector#30]
I was trying to look at a particular sequence of requests, but the visible requests keep scrolling out of view.  Maybe it's filled up a buffer and is pruning the older ones?   But it makes it a little hard to keep track of.  If nothing else, it'd be great to be able to pause the incoming stream.

![packets](https://cloud.githubusercontent.com/assets/95570/7077770/80996b24-dec8-11e4-9243-c669f981a998.gif)

**Comment by janodvarko** [comment]
I am not sure if I understand the problem, can you please provide detailed STR?

Btw. what version do you use?
Honza

**Comment by bgrins** [comment]
RDP inspector 1.0.2.  STR:

Open https://bgrins.github.io/devtools-demos/inspector/mutations.html
Open RDP inspector
Open Inspector tab in toolbox
Scroll all the way to the top of the viewport in RDP inspector and notice which packet you see
Wait for a while (15-20 seconds)
The packet disappears.  Now the visible packets keep changing every second, making it impossible figure out what happened in a particular sequence of packets because they keep on disappearing.

**Comment by janodvarko** [comment]
Ah, I see it now, thanks Brian!

Honza

**Comment by janodvarko** [comment]
The patch above implements a 'Pause' button that allows to pause the incoming stream of packets.

Honza
