### ISSUE TITLE
Pick an icon

### ISSUE THREAD

**Issue by janodvarko** [firebug/rdp-inspector#4]
An icon is needed for the extension

Honza

**Comment by SebastianZ** [comment]
What does the extension actually do? Knowing that it may be easier to think off an icon for it.

Sebastian

**Comment by janodvarko** [comment]
The main function is displaying traffic (send/received JSON packets) over an existing RDP connection, but there will be more, like showing registered actors on the backend. Mainly: it's an inspector, it's JSON packet visualizer.

Honza

**Comment by SebastianZ** [comment]
I see. So what about a symbol with two curly brackets and a magnifying glass?

Sebastian

**Comment by janodvarko** [comment]
1. I like a magnifying glass
2. Curly brackets look too close to Javascript
3. An 'inspector' can be represented by the magnifying glass or a person
4. A 'packet' can be represented by an envelop or a box
5. We might want a combination of those symbols
6. We need 16x16 and 32x32
7. We can also use a combo of monochromatic glyphicons (e.g. http://glyphicons.com/, http://getbootstrap.com/components/, etc.)
8. We can use an abstract symbol if none of our try looks professional (e.g. Pixel Perfect is using an abstract icon).

I am attaching some existing icons that demonstrates what we are close to.

![icon](https://cloud.githubusercontent.com/assets/37785/6958791/1faca23e-d911-11e4-9e55-6b3c6abf8be1.png)

Honza

**Comment by SebastianZ** [comment]
I'll try to come up with something.

**Comment by SebastianZ** [comment]
Here's a quick draft of what I had in mind:

![rdppacketinspector](https://cloud.githubusercontent.com/assets/958943/6961065/45e25ed2-d928-11e4-8174-85511d6efac9.png)

As it's related to packets, a box may be better than a letter.

Sebastian

**Comment by janodvarko** [comment]
Cool, nice draft

I wouldn't give up the letter symbol so quickly, it's RDP JSON "messages" what's sent over the wire after all, but box is good too.

Try also 16x16 it'll be harder I guess...

Honza

**Comment by SebastianZ** [comment]
The 16x16 version of the packet icon looks like this:
![16x16 version of the packet icon](https://cloud.githubusercontent.com/assets/958943/7019028/d5b390d0-dd0b-11e4-898f-30a8419bd001.png)

Here's a version with a letter (again, just a quick sketch):
![64x64 version of a letter icon](https://cloud.githubusercontent.com/assets/958943/7019033/e0ddd420-dd0b-11e4-96f9-631e531aae83.png)

And here the 16x16 version:
![16x16 version of the letter icon](https://cloud.githubusercontent.com/assets/958943/7019043/f5408b38-dd0b-11e4-9ff9-5d8df9996b56.png)

Sebastian

**Comment by janodvarko** [comment]
Sebastian, I applied the attached icon (envelop) since we want to do a first release. It already looks pretty good, just the small icon is a bit weak, it would deserve more love I think. I am attaching a screenshot.

![rdpicon](https://cloud.githubusercontent.com/assets/37785/7046049/73dc4ec6-de03-11e4-866f-cc7894c67eba.png)

Honza

**Comment by janodvarko** [comment]
Are you still planning to work on this?

Honza

**Comment by SebastianZ** [comment]
Yes, sorry for not being responsive the last days.

Sebastian

**Comment by SebastianZ** [comment]
Here is the final icon in different sizes:
64x64
![RDP Inspector icon 64x64](https://cloud.githubusercontent.com/assets/958943/7240560/44bfd9d8-e7b2-11e4-9fb6-a4f70fa5d6f4.png)

32x32
![RDP Inspector icon 32x32](https://cloud.githubusercontent.com/assets/958943/7240554/312be5ec-e7b2-11e4-82b6-721032bca676.png)

16x16
![RDP Inspector icon 16x16](https://cloud.githubusercontent.com/assets/958943/7240526/e716de94-e7b1-11e4-970b-ba02c8660b99.png)

The SVG version of the icon is sent via email to Honza, because GitHub doesn't allow to upload SVGs.

Sebastian

**Comment by janodvarko** [comment]
Excellent, and I've also got the svg version, it looks great, thanks Sebastian!

Closing this issue...

Honza
