### ISSUE TITLE
Going to need to update the module path for DevToolsUtils after Bug 912121 sticks

### ISSUE THREAD

**Issue by bgrins** [firebug/rdp-inspector#68]
In a local fxteam build, I see the following error.  In https://bugzilla.mozilla.org/show_bug.cgi?id=912121 the path to some devtools modules (including DevToolsUtils) has changed:

    console.error: rdpinspector: 
      Message: Module `devtools/toolkit/DevToolsUtils.js` is not found at resource://gre/modules/devtools/toolkit/DevToolsUtils.js
      Stack:
        @resource://rdpinspector-at-getfirebug-dot-com/node_modules/firebug.sdk/lib/core/window.js:13:28
    @resource://rdpinspector-at-getfirebug-dot-com/node_modules/firebug.sdk/lib/context.js:13:17
    @resource://rdpinspector-at-getfirebug-dot-com/node_modules/firebug.sdk/lib/toolbox-chrome.js:17:21
    @resource://rdpinspector-at-getfirebug-dot-com/lib/main.js:8:27
    @resource://rdpinspector-at-getfirebug-dot-com/index.js:32:15
    run@resource://gre/modules/commonjs/sdk/addon/runner.js:145:19
    startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
    Handler.prototype.process@resource://gre/modules/Promise-backend.js:934:23
    this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:813:7
    Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise-backend.js:744:11
    this.PromiseWalker.schedulePromise@resource://gre/modules/Promise-backend.js:776:7
    this.PromiseWalker.completePromise@resource://gre/modules/Promise-backend.js:711:7
    handler@resource://gre/modules/commonjs/sdk/addon/window.js:56:3

**Comment by bgrins** [comment]
As per @jryans, the new path is `devtools/shared/DevToolsUtils`

**Comment by janodvarko** [comment]
Is there any chance to detect the chance, so RDPi supports more Fx versions at the same time (previous and new paths)?

Honza

**Comment by jryans** [comment]
The strategies I can think of are:

* Check the version of Fx somewhere, use the right path based on that
* Try / catch loading the new path, fallback to old path if it fails
