### ISSUE TITLE
Error: Wrong State: Expected 'detached', but current state is 'attached'

### ISSUE THREAD

**Issue by janodvarko** [firebug/rdp-inspector#70]
STR:
1) Make sure to open at least one Toolbox
2) Open the connection list
3) Double click the entry to open RDPi console
4) Close the RDPi console
5) Double click the entry again, check out the Web console for the error.

Error: Wrong State: Expected 'detached', but current state is 'attached'
Stack trace:
expectState/<@resource://rdpinspector-at-getfirebug-dot-com/lib/inspector-actor.js:57:29
actorProto/</handler@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/protocol.js:1013:19
DSC_onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/main.js:1601:15
LocalDebuggerTransport.prototype.send/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/shared/transport/transport.js:569:11
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/shared/DevToolsUtils.js:87:14
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/shared/DevToolsUtils.js:87:14

Honza

**Comment by janodvarko** [comment]
@rpl any tips?

Honza

**Comment by rpl** [comment]
@janodvarko During the weekend I took a look at this:

we have a disconnect function in the inspectorActor that will be called when a connection is closed, but we are sharing the connection with the developer toolbox (or the WebIDE) and the debugging connection will not be closed when we close the inspector but when the toolbox itself is closed.

I've just pushed #71 which fix the issue in the above scenario, by explicitly detaching the actors when the RDPi window is closed.
