### ISSUE TITLE
The filter field doesn't seem to work anymore

### ISSUE THREAD

**Issue by janodvarko** [firebug/rdp-inspector#75]
I've a feeling that I broke it, but not sure where :-)

Honza

**Comment by rpl** [comment]
@janodvarko I'm pretty sure I broke it by not completing its wiring into the new redux architecture

#76 should fix this issue by correctly integrate the search filter with redux (and I've moved the action setSearchFilter in a new *global* reducer to make it clear that it is a filter applied to both the packets and actors panels)
