### ISSUE TITLE
WebIDE connection is not listed in the Connections window

### ISSUE THREAD

**Issue by janodvarko** [firebug/rdp-inspector#80]
Open RDP connection with a simulator (using WebIDE) and try to listen to the RDP packets. The problem is that the connection is not listed in the Connections window - the WebIDE tab is empty.

STR:
1) Open Web Developer -> WebIDE
2) Make sure you have at least one Simulator installed
3) Click on the Simulator in the Right panel -> you should see the Simulator window.
4) Open RDP Connections window using the toolbar-button dropdown menu: Connect...
5) The WebIDE tab is empty

Connecting through the Connect page should also be supported (Web Developer -> Connect ...)

Note: checking the 'Open automatically on new WebIDE connections' option doesn't work either. If I checked and re-open the menu, it's unchecked again.

Honza

**Comment by janodvarko** [comment]
@rpl: any tips what could be wrong?

Honza

**Comment by rpl** [comment]
@janodvarko currently the webide connections becomes visible only once a toolbox is opened, I've pushed some proposed changes in #81 to list the webide connections before the toolbox is opened and to enable the RDP Inspector to detect and monitor any other type of client RDP connection.
